export function nowISO(){ return new Date().toISOString(); }
export async function requestVip(name, txn){ const pending = JSON.parse(localStorage.getItem('pendingPayments') || '[]'); pending.push({ name, txn, date: nowISO() }); localStorage.setItem('pendingPayments', JSON.stringify(pending)); return true; }
export async function listPendingPayments(){ return JSON.parse(localStorage.getItem('pendingPayments') || '[]'); }
export async function validatePayment(txn, removeOnly=false){ const pending = JSON.parse(localStorage.getItem('pendingPayments') || '[]'); const idx = pending.findIndex(p=> p.txn === txn); if(idx === -1) return; const rec = pending[idx]; pending.splice(idx,1); localStorage.setItem('pendingPayments', JSON.stringify(pending)); if(!removeOnly){ const vipUsers = JSON.parse(localStorage.getItem('vipUsers') || '{}'); vipUsers[rec.name] = true; localStorage.setItem('vipUsers', JSON.stringify(vipUsers)); } }
export function isVipUser(name){ const vipUsers = JSON.parse(localStorage.getItem('vipUsers') || '{}'); return !!vipUsers[name]; }
export function genUID(seed='DEF'){ return (seed||'DEF').toUpperCase().replace(/[^A-Z0-9]+/g,'').slice(0,3) + '-' + Math.random().toString(36).slice(2,7).toUpperCase(); }
export function genOwnerCode(){ return Math.random().toString(36).slice(2,8).toUpperCase(); }
export async function generateRoom({ host, mode, questions }){ const uid = genUID(host); const ownerCode = genOwnerCode(); const rooms = JSON.parse(localStorage.getItem('rooms') || '{}'); rooms[uid] = { uid, ownerCode, host, avatar:'', mode, questions, createdAt: nowISO(), players: [] }; localStorage.setItem('rooms', JSON.stringify(rooms)); return rooms[uid]; }
export async function openRoomByUID(uid){ const rooms = JSON.parse(localStorage.getItem('rooms') || '{}'); return rooms[uid] || null; }
export async function submitPlayerResult(uid, player){ const rooms = JSON.parse(localStorage.getItem('rooms') || '{}'); const room = rooms[uid]; if(!room) throw new Error('Room introuvable'); room.players = room.players || []; room.players.push(player); rooms[uid] = room; localStorage.setItem('rooms', JSON.stringify(rooms)); const global = JSON.parse(localStorage.getItem('globalPlayers') || '[]'); global.push({ name: player.name, score: player.score, uid, date: player.date }); localStorage.setItem('globalPlayers', JSON.stringify(global)); }
export function listenRoomPlayers(uid, cb){ const rooms = JSON.parse(localStorage.getItem('rooms') || '{}'); const arr = (rooms[uid] && rooms[uid].players) ? rooms[uid].players.slice() : []; cb(arr); return ()=>{}; }
export async function getRoomPlayers(uid){ const rooms = JSON.parse(localStorage.getItem('rooms') || '{}'); return (rooms[uid] && rooms[uid].players) ? rooms[uid].players.slice().sort((a,b)=> b.score - a.score) : []; }
export async function getAllPlayersGlobal(){ const global = JSON.parse(localStorage.getItem('globalPlayers') || '[]'); return global.slice().sort((a,b)=> b.score - a.score); }
export async function ownerVerifyPlayer(uid, playerName){ const rooms = JSON.parse(localStorage.getItem('rooms') || '{}'); const room = rooms[uid]; if(!room) throw new Error('Room introuvable'); room.players = room.players || []; const p = room.players.find(pp=> pp.name === playerName); if(p) p.verified = true; rooms[uid] = room; localStorage.setItem('rooms', JSON.stringify(rooms)); }
export async function removeRoom(uid){ const rooms = JSON.parse(localStorage.getItem('rooms') || '{}'); delete rooms[uid]; localStorage.setItem('rooms', JSON.stringify(rooms)); }
